@BASE_URL =http://localhost:3000

###
GET {{BASE_URL}}/index

###
GET {{BASE_URL}}/index/getCityNames

###
GET {{BASE_URL}}/index/getBooks/Ankara/d
Content-Type: application/json

###
POST {{BASE_URL}}/bookStore/register
Content-Type: application/json

{
   "bookStoreName" : "warwar kirtasiye",
   "bookStoreContactNumber" : "555 555 55 55",
   "bookStoreContactEmail" : "wwdwdsa@gmail.com",
   "bookStoreUserName" : "wewe",
   "bookStorePassword" : "wewewewe",
   "bookStoreAddress" : "ankara wewe mah",
   "bookStoreCity" : "ankara",
   "bookStoreWebsite" : ""

}

###
POST {{BASE_URL}}/bookStore/login
Content-Type: application/json

{
    "bookStoreUserName" : "wewe",
    "bookStorePassword" : "wewewewe"
}

###
POST {{BASE_URL}}/bookStore/addBooks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGYyZDM5NDY0N2Q2ODhiZmM1YzBlYzgiLCJpYXQiOjE2OTM2NTUxNzUsImV4cCI6MTY5MzY1ODc3NX0.bEQgcA215NEXmKP6qwdXHaBtpP-ESy__vxh6UgYx51I

{
    "name" : "vvv",
    "publisher" : "pegasus",
    "author" : "mehmet",
    "stock" : "3",
    "publicationDate" : "23/04/2021",
    "pageCount" : "434",
    "ISBN" : "1234567821",
    "language" : "tr",
    "genre" : "action",
    "description" : "eeerrereee",
    "averageRating" : "3.5"
}

###
GET {{BASE_URL}}/bookStore/getMyBooks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGYyZDM5NDY0N2Q2ODhiZmM1YzBlYzgiLCJpYXQiOjE2OTM5ODUwNjUsImV4cCI6MTY5Mzk4ODY2NX0._DeGeHlX6SwwauwF5ii5DxDJejnisSrjJPq-kFlsG9w
###
GET {{BASE_URL}}/bookStore/findMyInfos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NGYyZDM5NDY0N2Q2ODhiZmM1YzBlYzgiLCJpYXQiOjE2OTM5ODIyNTAsImV4cCI6MTY5Mzk4NTg1MH0.6Lmxyb_10F_yDPubOwBPj9Y_FvBTwW794y-yHDg26TM

###
GET {{BASE_URL}}/index/getBooksByCity/Ankara/
Content-Type: application/json

###

DELETE {{BASE_URL}}/index/bookStoreDeleteBooks/1234567894
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTBjODgxZDMxNGFmNjQ4ZWNjMTc2YjAiLCJpYXQiOjE2OTUzNjY1NTIsImV4cCI6MTY5NTM3MDE1Mn0.-FgUILugC_WktneiIPOuKyoHMPcqLXAbHoTugvvk8kY

GET {{BASE_URL}}/bookStore/bulkAdd
Content-Type:  application/json
Authorization: 






